version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: stech_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8wLLlyI3kO3O6iDuDrrJrMmTxyrtbs4N3nEXBmUw2n18RelSER9BCXuphpYt0O4Y
      POSTGRES_DB: stech_db2
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stech-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stech_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stech_db2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8wLLlyI3kO3O6iDuDrrJrMmTxyrtbs4N3nEXBmUw2n18RelSER9BCXuphpYt0O4Y
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - stech-net

  adminer:
    image: adminer:latest
    container_name: stech_adminer
    restart: unless-stopped
    ports:
      - "8088:8080"  # <-- CORRIGIDO: Usa a porta 8088 externa para não conflituar com a 8080
    networks:
      - stech-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"] # ou wget
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata:

networks:
  stech-net:
    driver: bridge