spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

spring.application.name=pdv-backend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.jakarta.persistence.validation.mode=auto

spring.docker.compose.enabled=false

server.servlet.context-path=/

spring.jackson.time-zone=Africa/Maputo
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

logging.level.root=INFO
logging.level.com.stechengenharia.pdv_backend=INFO

spring.task.execution.pool.core-size=4

spring.flyway.enabled=false