# ===================================
# PERFIL ACTIVO
# ===================================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# ===================================
# APLICAÇÃO
# ===================================
spring.application.name=pdv-backend

# ===================================
# DRIVER JDBC
# ===================================
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# CONFIGURAÇÕES DO JPA/HIBERNATE
# ===================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Corrige problema com tipos LOB no PostgreSQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Desativa Open Session in View
spring.jpa.open-in-view=false

# ===================================
# DOCKER COMPOSE DO SPRING
# ===================================
spring.docker.compose.enabled=false

# ===================================
# CONFIGURAÇÕES DO SERVIDOR
# ===================================
server.port=8080
server.servlet.context-path=/

# ===================================
# CONFIGURAÇÕES DE ENCODING
# ===================================
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.jackson.time-zone=Africa/Maputo
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ===================================
# CONFIGURAÇÕES DE LOG
# ===================================
logging.level.root=INFO
logging.level.com.loja1.projectohibrido=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# ===================================
# HIKARI
# ===================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.initialization-fail-timeout=-1

# ===================================
# VALIDAÇÃO
# ===================================
spring.jpa.properties.jakarta.persistence.validation.mode=auto

# ===================================
# FIREBASE
# ===================================
firebase.service-account.path=firebase-service-account.json

# ===================================
# ASYNC
# ===================================
spring.task.execution.pool.core-size=4

# ===================================
# SYNC
# ===================================
sync.cloud.base-url=https://stech-pdv.onrender.com
sync.cloud.api-key=local-key-mock123
sync.api-key=local-endpoint-key-321

# ===================================
# FLYWAY
# ===================================
spring.flyway.enabled=false