name: Coolify Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -X GET "http://162.35.186.240:8000/api/v1/deploy?uuid=xlxnfxnx7yc0p4hw2t2khe71&force=false" \
               -H "Authorization: Bearer 1|0IaxA00OH6OBuX7CmJKUUiwvnVHrdcGSaezSzV4Hefbcd5a6"